export const emojiPrompts = [
  "Glowing Heart",
  "Girl with Rainbow Hair",
  "Shark with Tophat",
  "Crystal Crown",
  "Cat with Angel Wings",
  "Dancing Robot",
  "Rainbow Pizza",
  "Moonlit Forest",
  "Golden Owl",
  "Fire-Breathing Dragonfly",
  "Surfboard on Fire",
  "Holographic Butterfly",
  "Starry Night Umbrella",
  "Fox with Glasses",
  "Snowman Holding a Lantern",
  "Cosmic Jellyfish",
  "Cupcake with a Candle Hat",
  "Neon Skateboard",
  "Whale with Flower Garland",
  "Pirate Octopus",
  "Laughing with Tears of Stars",
  "Blushing with Fireworks",
  "Heartbreaking Sigh",
  "Overjoyed Sparkle Eyes",
  "Melting with Embarrassment",
  "Angry Storm Cloud",
  "Love-Struck Face with Hearts for Eyes",
  "Confused Spiral Head",
  "Crying with Raincloud Overhead",
  "Smug Face with Tilted Crown",
  "Mischievous Wink with Flame",
  "Shocked Face with Lightning Bolt",
  "Peaceful Smile with Floating Leaves",
  "Nervous Sweat Drip",
  "Dreamy Face with Halo",
  "Proud Face with Star Badge",
  "Exhausted Face with Zzz's",
  "Lonely Face Under Drooping Flower",
  "Ecstatic Face with Shooting Stars",
  "Thoughtful Face with Floating Lightbulb",
];

// prettier-ignore
export const emojiPrompts2 = [
"grinning cat with tears of joy",
"blushing smiling face with hearts",
"face screaming in joy",
"weary face with rolling eyes",
"smirking face with monocle",
"people holding hands with heart",
"face with sunglasses in love",
"puzzled face with question mark",
"confused face with steam coming out of nose",
"neutral face with balloons",
"person with veil riding a bike",
"firefighter with a megaphone",
"dancing person with sparkles",
"winking face with drum",
"bored face with sun",
"pregnant woman reading a book",
"smiling cat with coffee cup",
"face with medical mask and headphones",
"person with blond hair and laptop",
"face with tongue and party hat",
"person running with flag",
"crying face with bear",
"astonished face with fireworks",
"face with glasses in bathtub",
"face with party blower and confetti",
"sleepy face with rainbow",
"person in lotus position with sheep",
"face with open mouth and snowy mountain",
"superhero with microscope",
"person shrugging with pizza",
"face with rolling eyes on a skateboard",
"face savoring food with utensils",
"nerd face with video game controller",
"ballet shoes with world map",
"person kneeling with flower bouquet",
"happy face with books",
"face with zippered mouth at night",
"face with monocle at microscope",
"ghost with computer",
"face vomiting with party popper"
]
// prettier-ignore
export const emojiIdeas: { name: string; category: string; description: string }[] = [
  // Nature & Environment
  { name: "Melting Glacier", category: "Nature & Environment", description: "A small mountain of ice half-submerged in water." },
  { name: "Blooming Flower", category: "Nature & Environment", description: "A time-lapse style flower bud opening." },
  { name: "Solar Eclipse", category: "Nature & Environment", description: "A sun partially covered by the moon with a glowing corona." },
  { name: "Forest Fire", category: "Nature & Environment", description: "Trees with flames, symbolizing wildfire awareness." },
  { name: "Water Drops and Fire", category: "Nature & Environment", description: "Juxtaposed elements showing blue water droplets alongside bright flames." },

  // Food & Drinks
  { name: "Bubble Tea", category: "Food & Drinks", description: "A bubble tea cup featuring tapioca pearls in clear view." },
  { name: "Burnt Toast", category: "Food & Drinks", description: "A humorously charred piece of bread." },
  { name: "Champagne Tower", category: "Food & Drinks", description: "Glasses stacked in a celebratory pyramid." },
  { name: "Spicy Chili", category: "Food & Drinks", description: "A cartoonishly red-hot pepper with smoke curling out." },

  // Technology & Science
  { name: "AI Brain", category: "Technology & Science", description: "A brain made of circuit lines, glowing slightly." },
  { name: "Hologram", category: "Technology & Science", description: "A futuristic glowing figure, possibly blue or green." },
  { name: "Microscope Slide", category: "Technology & Science", description: "Representing laboratory experiments or education." },
  { name: "Electric Scooter", category: "Technology & Science", description: "For modern urban commuting." },

  // Emotions & Expressions
  { name: "Facepalm Explosion", category: "Emotions & Expressions", description: "A head holding itself as a mini explosion goes off." },
  { name: "Nervous Sweat", category: "Emotions & Expressions", description: "A worried face with a bead of sweat and a nervous smile." },
  { name: "Yawning Cat", category: "Emotions & Expressions", description: "A sleepy cat mid-yawn." },
  { name: "Heart Bubble", category: "Emotions & Expressions", description: "A heart encapsulated in a floating soap bubble." },
  { name: "Smile with Broken Teeth", category: "Emotions & Expressions", description: "A grin with one or more chipped or missing teeth, showing resilience or awkwardness." },

  // Activities & Hobbies
  { name: "Origami Crane", category: "Activities & Hobbies", description: "Folded paper art." },
  { name: "Rock Climbing", category: "Activities & Hobbies", description: "A climber on a steep rock face." },
  { name: "Retro Game Console", category: "Activities & Hobbies", description: "Nostalgic nod to pixel-based gaming." },
  { name: "Dance Floor", category: "Activities & Hobbies", description: "A disco ball over a colorful, glowing floor." },
  { name: "Girl Gardening", category: "Activities & Hobbies", description: "A cheerful girl tending to a plant or flowers with a watering can or gardening tools." },

  // Fashion & Accessories
  { name: "High-Tech Glasses", category: "Fashion & Accessories", description: "AR/VR glasses with a digital overlay." },
  { name: "Tie-Dye Shirt", category: "Fashion & Accessories", description: "A swirl of vibrant colors on fabric." },
  { name: "Sneakers", category: "Fashion & Accessories", description: "High-detail trainers with trendy designs." },
  { name: "Seashell Necklace", category: "Fashion & Accessories", description: "Coastal vibes." },

  // Fantasy & Magic
  { name: "Crystal Ball", category: "Fantasy & Magic", description: "A glowing orb with swirling mist inside." },
  { name: "Potion Bottle", category: "Fantasy & Magic", description: "Bubbling, colorful liquid in an ornate flask." },
  { name: "Dragon Egg", category: "Fantasy & Magic", description: "An egg with faint glowing cracks." },
  { name: "Magic Wand", category: "Fantasy & Magic", description: "Star-tipped with sparkling effects." },

  // Miscellaneous
  { name: "Girl with Tomato", category: "Miscellaneous", description: "A playful girl holding or presenting a tomato, symbolizing gardening, cooking, or freshness." },
];
